### ISSUE TITLE
Info singleton class?

### ISSUE THREAD

**Issue by ignatandrei** [kzu/ThisAssembly#11]
Could you please generate a (singleton ) class for Info ? 
I want to make a controller action and return

[HttpGet]
    public Info Version()
    {
      return ThisAssembly.Info.Singleton();
    }

instead of returning one by one

**Comment by kzu** [comment]
You could create a method that uses reflection to introspect all public fields of the class and generates a JSON object with all values to return from any endpoint. Would that be enough?

**Comment by ignatandrei** [comment]
I do not like reflection at all. I can make a PR with the changes, if you agree with the proposal

**Comment by kzu** [comment]
I do not like singletons at all :P.

You can trivially cache your singleton with one-time-only reflection of the info class and keep it alive as long as the app lives. It's not like it will have a significant perf. impact IMHO.

So, unfortunately, no, I don't think the use case justifies adding this. But since all ThisAssembly classes are partial, you can most certainly create your own source generator that exposes what you need by just generating another partial that extends the ThisAssembly.Info partial class.
