### ISSUE TITLE
net5.0-windows

### ISSUE THREAD

**Issue by archi-Doc** [kzu/ThisAssembly#14]
Hi,
I tried ThisAssenbly for a console app, and it worked perfectly.
But didn't work for a windows app.

```error CS0103: The name 'ThisAssembly' does not exist in the current context```

csproj file is

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ThisAssembly" Version="1.0.0" />
  </ItemGroup>

</Project>
```

Looks like ThisAssemly generates correct code and I can see the generated code, but windows app can't reference those code.

**Comment by kzu** [comment]
This is due to a bug in WPF: https://github.com/dotnet/wpf/issues/3404. 
The workaround is https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#wpf-projects-unable-to-generate-grpc-c-assets-from-proto-files (basically use a class library instead, quite the #fail).

Since this is not something we can fix in this project, I'm going to tentatively close it. Please do reopen if there is an actual fix at some point and we need to do something on this project.

Thanks!

**Comment by kzu** [comment]
This search shields a potential manual workaround alternative for your own repo: https://github.com/dotnet/arcade/search?q=_WpfTempProjectNuGetFilePathNoExt

**Comment by archi-Doc** [comment]
Thanks for the reply.
I'll wait for Microsoft to resolve this issue.

**Comment by springy76** [comment]
Doesn't work within Blazor(server) apps as well.

**Comment by kzu** [comment]
@springy76 could you link to the relevant MS issue on their side too, in case they are aware, so others can also track that as needed?
